on: [push, pull_request]
name: Test Build
jobs:
  build-on-winarm64:
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          architecture: 'x64'
      - name: test
        run: make i test
      - name: build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: make winarm64
